feat(backend): [PYTA-20] Add dummy data
projekt-zespolowy-ug/P.Y.T.A pull request #24
Opened 2024-11-06 19:44 UTC by malekk1

2024-11-06 23:15 UTC, olszewskista requested changes

2024-11-06 23:15 UTC, olszewskista commented on backend/pyproject.toml
> +indent-style = "space"
change it back to tab

2024-11-07 18:09 UTC, Memetelve commented on backend/app/core/utils/querying_utils.py
> +	def hash_password(password: Any) -> Any:
there is a possibility to type this properly as 
`def hash_password(password: str) -> str:`
 when you also type Auth.password as TextField | str and implicitly convert to str while passing Auth.passoword as argument 
`hash_password(str(self.password))`

2024-11-07 18:58 UTC, Memetelve approved these changes
i suggest we merge it, to allow the change from peewee to sqlmodel. Code is overall good, minor issues that shouldn't be blocking this

2024-11-09 12:16 UTC, Memetelve approved these changes

2024-11-09 12:17 UTC, olszewskista approved these changes

2024-11-09 12:17 UTC, merged